site_name: Valedocode Documentation
repo_url: https://github.com/JamesOliverRobinson/DocumentationSite
repo_name: GitHub repository
nav:
  - Home: index.md
  - Guide Catalogue: about.md
theme: readthedocs

