name: build

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: cd child-site; mkdocs build
      - run: mkdir parent-site/doc/docs/child-site
      - run: cp -a child-site/site/. parent-site/doc/docs/child-site
      - run: cd parent-site; mkdocs gh-deploy -f
