name: publish-documentation

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: zulu
      - name: Install graphviz
        run: sudo apt install graphviz
      - name: Get jar
        run: |
          wget https://kumisystems.dl.sourceforge.net/project/plantuml/1.2022.5/plantuml.1.2022.5.jar -o myfile.jar
      - name: Check present
        run: ls
      - name: generate
        run: java -jar myfile.jar -verbose test.puml


